<?php 
	$conex = mysqli_connect("localhost","root","","registro");
	//REALIZAMOS LA CONEXION CON LA BASE DE DATOS PASANDOLE A CONEX, EL LOCALHOSTM EL ROOT, CONTRASEÑA Y EL REGISTRO QUE ES EL NOMBRE DE LA BASE DE DATOS
?>


